//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_BlogPostType
    {
        public Fly_BlogPostType()
        {
            this.Fly_BlogPost = new HashSet<Fly_BlogPost>();
        }
    
        public int BlogPostTypeID { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<Fly_BlogPost> Fly_BlogPost { get; set; }
    }
}
