//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Navigation
    {
        public Fly_Navigation()
        {
            this.Fly_Navigation1 = new HashSet<Fly_Navigation>();
        }
    
        public int navid { get; set; }
        public string title_vn { get; set; }
        public string title_en { get; set; }
        public string href { get; set; }
        public Nullable<int> parentid { get; set; }
        public string imgLink { get; set; }
        public string ico { get; set; }
        public string classObj { get; set; }
        public string idObj { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<Fly_Navigation> Fly_Navigation1 { get; set; }
        public virtual Fly_Navigation Fly_Navigation2 { get; set; }
    }
}
