//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Order
    {
        public Fly_Order()
        {
            this.Fly_DiscountUsageHistory = new HashSet<Fly_DiscountUsageHistory>();
            this.Fly_OrderNote = new HashSet<Fly_OrderNote>();
            this.Fly_OrderProductVariant = new HashSet<Fly_OrderProductVariant>();
        }
    
        public int OrderID { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ApproveID { get; set; }
        public string CustomerIP { get; set; }
        public string TaxRates { get; set; }
        public Nullable<decimal> OrderTax { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<decimal> RefundedAmount { get; set; }
        public Nullable<decimal> OrderDiscount { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentMethodName { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string BillingFirstName { get; set; }
        public string BillingLastName { get; set; }
        public string BillingPhoneNumber { get; set; }
        public string BillingEmail { get; set; }
        public string BillingFaxNumber { get; set; }
        public string BillingCompany { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingCity { get; set; }
        public Nullable<int> BillingCountryID { get; set; }
        public Nullable<int> ShippingStatusID { get; set; }
        public Nullable<int> ShippingMethodID { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Fly_Country Fly_Country { get; set; }
        public virtual Fly_Customer Fly_Customer { get; set; }
        public virtual Fly_Customer Fly_Customer1 { get; set; }
        public virtual ICollection<Fly_DiscountUsageHistory> Fly_DiscountUsageHistory { get; set; }
        public virtual Fly_ShippingMethod Fly_ShippingMethod { get; set; }
        public virtual Fly_ShippingStatus Fly_ShippingStatus { get; set; }
        public virtual ICollection<Fly_OrderNote> Fly_OrderNote { get; set; }
        public virtual ICollection<Fly_OrderProductVariant> Fly_OrderProductVariant { get; set; }
    }
}
