//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Category
    {
        public Fly_Category()
        {
            this.Fly_Category_Discount_Mapping = new HashSet<Fly_Category_Discount_Mapping>();
            this.Fly_CategoryLocalized = new HashSet<Fly_CategoryLocalized>();
            this.Fly_Product_Category_Mapping = new HashSet<Fly_Product_Category_Mapping>();
        }
    
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<bool> ShowOnHomePage { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<Fly_Category_Discount_Mapping> Fly_Category_Discount_Mapping { get; set; }
        public virtual Fly_Picture Fly_Picture { get; set; }
        public virtual ICollection<Fly_CategoryLocalized> Fly_CategoryLocalized { get; set; }
        public virtual ICollection<Fly_Product_Category_Mapping> Fly_Product_Category_Mapping { get; set; }
    }
}
