//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Category_Discount_Mapping
    {
        public int CategoryDiscountMappingID { get; set; }
        public int CategoryID { get; set; }
        public int DiscountID { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
    
        public virtual Fly_Category Fly_Category { get; set; }
        public virtual Fly_Discount Fly_Discount { get; set; }
    }
}
