//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_OrderNote
    {
        public int OrderNoteID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Note { get; set; }
        public Nullable<bool> DisplayToCustomer { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Fly_Order Fly_Order { get; set; }
    }
}
