//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Discount
    {
        public Fly_Discount()
        {
            this.Fly_Category_Discount_Mapping = new HashSet<Fly_Category_Discount_Mapping>();
            this.Fly_CustomerRole_Discount_Mapping = new HashSet<Fly_CustomerRole_Discount_Mapping>();
            this.Fly_DiscountUsageHistory = new HashSet<Fly_DiscountUsageHistory>();
            this.Fly_ProductVariant_Discount_Mapping = new HashSet<Fly_ProductVariant_Discount_Mapping>();
        }
    
        public int DiscountID { get; set; }
        public Nullable<int> LimitationTimes { get; set; }
        public string Name { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual ICollection<Fly_Category_Discount_Mapping> Fly_Category_Discount_Mapping { get; set; }
        public virtual ICollection<Fly_CustomerRole_Discount_Mapping> Fly_CustomerRole_Discount_Mapping { get; set; }
        public virtual ICollection<Fly_DiscountUsageHistory> Fly_DiscountUsageHistory { get; set; }
        public virtual ICollection<Fly_ProductVariant_Discount_Mapping> Fly_ProductVariant_Discount_Mapping { get; set; }
    }
}
