//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Language
    {
        public Fly_Language()
        {
            this.Fly_BlogPost = new HashSet<Fly_BlogPost>();
            this.Fly_CategoryLocalized = new HashSet<Fly_CategoryLocalized>();
            this.Fly_ManufacturerLocalized = new HashSet<Fly_ManufacturerLocalized>();
            this.Fly_ProductLocalized = new HashSet<Fly_ProductLocalized>();
            this.Fly_ProductVariantLocalized = new HashSet<Fly_ProductVariantLocalized>();
            this.Fly_ShippingMethod = new HashSet<Fly_ShippingMethod>();
        }
    
        public int LanguageId { get; set; }
        public string Name { get; set; }
        public string LanguageCulture { get; set; }
        public string FlagImageFileName { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual ICollection<Fly_BlogPost> Fly_BlogPost { get; set; }
        public virtual ICollection<Fly_CategoryLocalized> Fly_CategoryLocalized { get; set; }
        public virtual ICollection<Fly_ManufacturerLocalized> Fly_ManufacturerLocalized { get; set; }
        public virtual ICollection<Fly_ProductLocalized> Fly_ProductLocalized { get; set; }
        public virtual ICollection<Fly_ProductVariantLocalized> Fly_ProductVariantLocalized { get; set; }
        public virtual ICollection<Fly_ShippingMethod> Fly_ShippingMethod { get; set; }
    }
}
