//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_ShoppingCartItem
    {
        public int ShoppingCartItemID { get; set; }
        public Nullable<System.Guid> CustomerSessionGUID { get; set; }
        public Nullable<int> ProductVariantID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> Prices { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Fly_Customer Fly_Customer { get; set; }
        public virtual Fly_CustomerSession Fly_CustomerSession { get; set; }
        public virtual Fly_ProductVariant Fly_ProductVariant { get; set; }
    }
}
