//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_DiscountUsageHistory
    {
        public int DiscountUsageHistoryID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Fly_Customer Fly_Customer { get; set; }
        public virtual Fly_Discount Fly_Discount { get; set; }
        public virtual Fly_Order Fly_Order { get; set; }
    }
}
