//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_ProductTemplate
    {
        public Fly_ProductTemplate()
        {
            this.Fly_Product = new HashSet<Fly_Product>();
        }
    
        public int ProductTemplateId { get; set; }
        public string Name { get; set; }
        public string TemplatePath { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<Fly_Product> Fly_Product { get; set; }
    }
}
