//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_ProductLocalized
    {
        public int ProductLocalizedID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
    
        public virtual Fly_Language Fly_Language { get; set; }
        public virtual Fly_Product Fly_Product { get; set; }
    }
}
