//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_CustomerSession
    {
        public Fly_CustomerSession()
        {
            this.Fly_ShoppingCartItem = new HashSet<Fly_ShoppingCartItem>();
        }
    
        public System.Guid CustomerSessionGUID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> LastAccessed { get; set; }
        public Nullable<bool> IsExpired { get; set; }
    
        public virtual Fly_Customer Fly_Customer { get; set; }
        public virtual ICollection<Fly_ShoppingCartItem> Fly_ShoppingCartItem { get; set; }
    }
}
