//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_OrderProductVariant
    {
        public int OrderProductVariantID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductVariantID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<System.Guid> OrderProductVariantGUID { get; set; }
    
        public virtual Fly_Order Fly_Order { get; set; }
        public virtual Fly_ProductVariant Fly_ProductVariant { get; set; }
    }
}
