//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Customer
    {
        public Fly_Customer()
        {
            this.Fly_Banner = new HashSet<Fly_Banner>();
            this.Fly_BannerType = new HashSet<Fly_BannerType>();
            this.Fly_BlogPost = new HashSet<Fly_BlogPost>();
            this.Fly_Customer_CustomerRole_Mapping = new HashSet<Fly_Customer_CustomerRole_Mapping>();
            this.Fly_CustomerAttribute = new HashSet<Fly_CustomerAttribute>();
            this.Fly_CustomerSession = new HashSet<Fly_CustomerSession>();
            this.Fly_DiscountUsageHistory = new HashSet<Fly_DiscountUsageHistory>();
            this.Fly_Order = new HashSet<Fly_Order>();
            this.Fly_Order1 = new HashSet<Fly_Order>();
            this.Fly_Partnership = new HashSet<Fly_Partnership>();
            this.Fly_ShoppingCartItem = new HashSet<Fly_ShoppingCartItem>();
            this.Fly_Videos = new HashSet<Fly_Videos>();
        }
    
        public int CustomerID { get; set; }
        public Nullable<System.Guid> CustomerGUID { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<bool> IsTaxExempt { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsGuest { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> AvatarID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual ICollection<Fly_Banner> Fly_Banner { get; set; }
        public virtual ICollection<Fly_BannerType> Fly_BannerType { get; set; }
        public virtual ICollection<Fly_BlogPost> Fly_BlogPost { get; set; }
        public virtual ICollection<Fly_Customer_CustomerRole_Mapping> Fly_Customer_CustomerRole_Mapping { get; set; }
        public virtual Fly_Picture Fly_Picture { get; set; }
        public virtual ICollection<Fly_CustomerAttribute> Fly_CustomerAttribute { get; set; }
        public virtual ICollection<Fly_CustomerSession> Fly_CustomerSession { get; set; }
        public virtual ICollection<Fly_DiscountUsageHistory> Fly_DiscountUsageHistory { get; set; }
        public virtual ICollection<Fly_Order> Fly_Order { get; set; }
        public virtual ICollection<Fly_Order> Fly_Order1 { get; set; }
        public virtual ICollection<Fly_Partnership> Fly_Partnership { get; set; }
        public virtual ICollection<Fly_ShoppingCartItem> Fly_ShoppingCartItem { get; set; }
        public virtual ICollection<Fly_Videos> Fly_Videos { get; set; }
    }
}
