//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Product_Category_Mapping
    {
        public int ProductCategoryID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> IsFeaturedProduct { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual Fly_Category Fly_Category { get; set; }
        public virtual Fly_Product Fly_Product { get; set; }
    }
}
