//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Country
    {
        public Fly_Country()
        {
            this.Fly_CustomerAttribute = new HashSet<Fly_CustomerAttribute>();
            this.Fly_Order = new HashSet<Fly_Order>();
        }
    
        public int CountryID { get; set; }
        public string Name { get; set; }
        public string TwoLetterISOCode { get; set; }
        public string ThreeLetterISOCode { get; set; }
        public Nullable<int> NumericISOCode { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual ICollection<Fly_CustomerAttribute> Fly_CustomerAttribute { get; set; }
        public virtual ICollection<Fly_Order> Fly_Order { get; set; }
    }
}
