//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_PaymentMethod
    {
        public int PaymentMethodID { get; set; }
        public string Name { get; set; }
        public string VisibleName { get; set; }
        public string Description { get; set; }
        public string ConfigureTemplatePath { get; set; }
        public string UserTemplatePath { get; set; }
        public string ClassName { get; set; }
        public string SystemKeyword { get; set; }
        public bool IsActive { get; set; }
        public int DisplayOrder { get; set; }
    }
}
