//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Product_Manufacturer_Mapping
    {
        public int ProductManufacturerID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<bool> IsFeaturedProduct { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual Fly_Manufacturer Fly_Manufacturer { get; set; }
        public virtual Fly_Product Fly_Product { get; set; }
    }
}
