//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_CustomerRole_ProductPrice
    {
        public int CustomerRoleProductPriceID { get; set; }
        public Nullable<int> CustomerRoleID { get; set; }
        public Nullable<int> ProductVariantID { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Fly_CustomerRole Fly_CustomerRole { get; set; }
        public virtual Fly_ProductVariant Fly_ProductVariant { get; set; }
    }
}
