//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Product
    {
        public Fly_Product()
        {
            this.Fly_Product_Category_Mapping = new HashSet<Fly_Product_Category_Mapping>();
            this.Fly_Product_Manufacturer_Mapping = new HashSet<Fly_Product_Manufacturer_Mapping>();
            this.Fly_ProductLocalized = new HashSet<Fly_ProductLocalized>();
            this.Fly_ProductPicture = new HashSet<Fly_ProductPicture>();
            this.Fly_ProductVariant = new HashSet<Fly_ProductVariant>();
            this.Fly_RelatedProduct = new HashSet<Fly_RelatedProduct>();
            this.Fly_SectionContent = new HashSet<Fly_SectionContent>();
            this.Fly_SectionGallery = new HashSet<Fly_SectionGallery>();
            this.Fly_Videos = new HashSet<Fly_Videos>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public Nullable<bool> ShowOnHomePage { get; set; }
        public Nullable<bool> isAccessories { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<Fly_Product_Category_Mapping> Fly_Product_Category_Mapping { get; set; }
        public virtual Fly_ProductTemplate Fly_ProductTemplate { get; set; }
        public virtual ICollection<Fly_Product_Manufacturer_Mapping> Fly_Product_Manufacturer_Mapping { get; set; }
        public virtual ICollection<Fly_ProductLocalized> Fly_ProductLocalized { get; set; }
        public virtual ICollection<Fly_ProductPicture> Fly_ProductPicture { get; set; }
        public virtual ICollection<Fly_ProductVariant> Fly_ProductVariant { get; set; }
        public virtual ICollection<Fly_RelatedProduct> Fly_RelatedProduct { get; set; }
        public virtual ICollection<Fly_SectionContent> Fly_SectionContent { get; set; }
        public virtual ICollection<Fly_SectionGallery> Fly_SectionGallery { get; set; }
        public virtual ICollection<Fly_Videos> Fly_Videos { get; set; }
    }
}
