//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_BannerType
    {
        public Fly_BannerType()
        {
            this.Fly_Banner = new HashSet<Fly_Banner>();
        }
    
        public int BannerTypeID { get; set; }
        public string BannerTypeTitle { get; set; }
        public string BannerTypeShortContent { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual ICollection<Fly_Banner> Fly_Banner { get; set; }
        public virtual Fly_Customer Fly_Customer { get; set; }
    }
}
