//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Banner
    {
        public int BannerID { get; set; }
        public Nullable<int> BannerTypeID { get; set; }
        public string BannerTitle { get; set; }
        public string BannerShortContent { get; set; }
        public string BannerLink { get; set; }
        public Nullable<System.DateTime> BannerTimeFrom { get; set; }
        public Nullable<System.DateTime> BannerTimeTo { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual Fly_BannerType Fly_BannerType { get; set; }
        public virtual Fly_Customer Fly_Customer { get; set; }
        public virtual Fly_Picture Fly_Picture { get; set; }
    }
}
