//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_SectionContent
    {
        public Fly_SectionContent()
        {
            this.Fly_Videos = new HashSet<Fly_Videos>();
        }
    
        public int SectionContentID { get; set; }
        public Nullable<int> PositionGalleryID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string FullDescription { get; set; }
        public string FullDescription_EN { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    
        public virtual Fly_PositionGallery Fly_PositionGallery { get; set; }
        public virtual Fly_Product Fly_Product { get; set; }
        public virtual ICollection<Fly_Videos> Fly_Videos { get; set; }
    }
}
