//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Videos
    {
        public int VideosID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string VideosTitle { get; set; }
        public string VideosShortContent { get; set; }
        public string VideosLink { get; set; }
        public Nullable<int> SectionContentID { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<bool> isShowHome { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual Fly_Customer Fly_Customer { get; set; }
        public virtual Fly_Picture Fly_Picture { get; set; }
        public virtual Fly_PositionGallery Fly_PositionGallery { get; set; }
        public virtual Fly_Product Fly_Product { get; set; }
        public virtual Fly_SectionContent Fly_SectionContent { get; set; }
    }
}
