//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Picture
    {
        public Fly_Picture()
        {
            this.Fly_Banner = new HashSet<Fly_Banner>();
            this.Fly_Category = new HashSet<Fly_Category>();
            this.Fly_Customer = new HashSet<Fly_Customer>();
            this.Fly_Manufacturer = new HashSet<Fly_Manufacturer>();
            this.Fly_Partnership = new HashSet<Fly_Partnership>();
            this.Fly_ProductPicture = new HashSet<Fly_ProductPicture>();
            this.Fly_Videos = new HashSet<Fly_Videos>();
        }
    
        public int PictureID { get; set; }
        public byte[] PictureBinary { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public string OriginalURL { get; set; }
        public string MimeType { get; set; }
    
        public virtual ICollection<Fly_Banner> Fly_Banner { get; set; }
        public virtual ICollection<Fly_Category> Fly_Category { get; set; }
        public virtual ICollection<Fly_Customer> Fly_Customer { get; set; }
        public virtual ICollection<Fly_Manufacturer> Fly_Manufacturer { get; set; }
        public virtual ICollection<Fly_Partnership> Fly_Partnership { get; set; }
        public virtual ICollection<Fly_ProductPicture> Fly_ProductPicture { get; set; }
        public virtual ICollection<Fly_Videos> Fly_Videos { get; set; }
    }
}
