//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_Manufacturer
    {
        public Fly_Manufacturer()
        {
            this.Fly_ManufacturerLocalized = new HashSet<Fly_ManufacturerLocalized>();
            this.Fly_Product_Manufacturer_Mapping = new HashSet<Fly_Product_Manufacturer_Mapping>();
        }
    
        public int ManufacturerID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Fly_Picture Fly_Picture { get; set; }
        public virtual ICollection<Fly_ManufacturerLocalized> Fly_ManufacturerLocalized { get; set; }
        public virtual ICollection<Fly_Product_Manufacturer_Mapping> Fly_Product_Manufacturer_Mapping { get; set; }
    }
}
