//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fly_PositionGallery
    {
        public Fly_PositionGallery()
        {
            this.Fly_SectionContent = new HashSet<Fly_SectionContent>();
            this.Fly_SectionGallery = new HashSet<Fly_SectionGallery>();
            this.Fly_Videos = new HashSet<Fly_Videos>();
        }
    
        public int PositionGalleryID { get; set; }
        public string PositionName { get; set; }
        public string PositionName_EN { get; set; }
        public Nullable<bool> isContent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<Fly_SectionContent> Fly_SectionContent { get; set; }
        public virtual ICollection<Fly_SectionGallery> Fly_SectionGallery { get; set; }
        public virtual ICollection<Fly_Videos> Fly_Videos { get; set; }
    }
}
